### PR TITLE
Add Barrett 2050 backend

### PR DESCRIPTION
**Pull request by mdblack98**

### CODE REVIEW

**Comment by N0NB** [comment]
I don't see an actual barret backend, Mike.  :-)

**Comment by mdblack98** [comment]
Oh crap....I missed adding the directory....
I'll have it shortly.... 
----------------------------------- 
Michael D. Black

**Comment by mdblack98** [comment]
I just committed the rest of the files.  Do I need to re-do the pull request?  It looks like it incorporated it.
de Mike W9MDB

**Comment by N0NB** [comment]
Applied and pushed.  Be aware that I had to do a small fixup to Makefile.am (trailing space complaint from Autotools), so I rebased everything to your original commit.  You will need to make sure your master branch gets in sync with mine.

**Comment by mdblack98** [comment]
OK...thanks....
Another warning I see when building is probably minor...but not sure what the intent is...
ar: `u' modifier ignored since `D' is the default (see `U')

So the archive is being built without date/time/user/group by default.  But is that the intent?  Perhaps we want "ar uU"  instead of the default "ar uD" ??
de MIke W9MDB

**Comment by N0NB** [comment]
* On 2017 04 Jul 13:12 -0500, mdblack98 wrote:
> OK...thanks....
> Another warning I see when building is probably minor...but not sure what the intent is...
> ar: `u' modifier ignored since `D' is the default (see `U')

Scratches head.  Eh?

> So the archive is being built without date/time/user/group by
> default.  But is that the intent?  Perhaps we want "ar uU"  instead of
> the default "ar uD" ??

Must be something that comes from the build system I'm not seeing here
on Devuan Jessie.

My laptop is now Slackware 14.2 current which has GCC 7.x, as I recall.
I'll do some test builds on it in the coming days.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by mdblack98** [comment]
Probably the ar version...
GNU ar (GNU Binutils for Ubuntu) 2.28
Mike

**Comment by N0NB** [comment]
* On 2017 04 Jul 13:32 -0500, mdblack98 wrote:
> Probably the ar version...
> GNU ar (GNU Binutils for Ubuntu) 2.28

Mine is still:

     GNU ar (GNU Binutils for Debian) 2.25

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Pull request closed without merging**
