### PR TITLE
Fixed SCAN_STOP for all rigs and implmented it plus SCOPE for ic7300

### PR DESCRIPTION
**Pull request by mdblack98**

### CODE REVIEW

**Comment by N0NB** [comment]
Looks good.  Thanks, Mike.

**Comment by mdblack98** [comment]
Nate,I guess if I create a pull request on my github fork that you get automagically notified?
I'd think having the pull request via the mailing list is a bit better as it would prompt others to check it out a bit more.
Mike

**Comment by N0NB** [comment]
* On 2016 03 Jun 07:24 -0500, mdblack98 wrote:
> Nate,I guess if I create a pull request on my github fork that you get
> automagically notified?

Yup, GH sends me a mail.  Also if you were to add a comment to the
PR/issue/comment on code, I get a mail, etc.

> I'd think having the pull request via the mailing list is a bit better
> as it would prompt others to check it out a bit more.

Feel free to make a posting to the mailing list with your PRs, but I
don't know of a way to add a CC to the GH notifications.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by mdblack98** [comment]
Reason I asked is I saw two merges in the log
I've got another small patch coming so would like to do that whatever method is best. ----------------------------------- 
Michael D. Black

**Comment by N0NB** [comment]
* On 2016 03 Jun 08:22 -0500, mdblack98 wrote:
> Reason I asked is I saw two merges in the log

Seems to be a quick of using the GH Web interface.  I'll try a pull from
my local repository to see if it avoids the second commit.

> I've got another small patch coming so would like to do that whatever
> method is best.

Do it as the prior one.  That works well for me.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Pull request merged**
