### PR TITLE
Fixed indentation warnings detected by newer gcc

### PR DESCRIPTION
**Pull request by mdblack98**
Fixed one error discovered by these warnings in easycomm.c

### CODE REVIEW

**Comment by N0NB** [comment]
Applied and pushed.  Thanks, Mike.

Perhaps we should consider it a rule from now on that all if, for,
do/while blocks have braces around there following block.  I know I will
look at that more closely.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by mdblack98** [comment]
I got in the habit of adding braces everywhere after adding lines outside of scope a few times.
I also think we should run all the code through indent with a standard format and no tabs as the indenting is horribly inconsistent.
Something like:
indent -kr --no-tabs
At least that's my favorite format
de Mike W9MDB

**Comment by N0NB** [comment]
* On 2017 28 Jun 16:59 -0500, mdblack98 wrote:
> 
> 
> 
> I got in the habit of adding braces everywhere after adding lines
> outside of scope a few times.

> I also think we should run all the code through indent with a standard
> format and no tabs as the indenting is horribly inconsistent.

> Something like:
> indent -kr --no-tabs
> At least that's my favorite format

I have an astyle config file in the scripts directory.  At one time I
set about formatting files using astyle.  I like that it does more
formatting than just indents.  There are a lot of "styles" in Hamlib,
and I really should just bite the bullet and do the formatting, I guess.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by mdblack98** [comment]
I'd recommend getting rid of the tabs line in astyle.  That's what caused the problem with the indentation warnings I think plus tab spacings aren't portable.Just stick with 4 spaces per indent as the default or explicitly.
Mike

**Comment by N0NB** [comment]
* On 2017 28 Jun 22:56 -0500, mdblack98 wrote:
> I'd recommend getting rid of the tabs line in astyle.  That's what
> caused the problem with the indentation warnings I think plus tab
> spacings aren't portable.Just stick with 4 spaces per indent as the
> default or explicitly.

I'm leaning that direction these days.  That amount of spacing is a nice
compromise as I've found when playing with Python.

I will update the astylerc file.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by N0NB** [comment]
* On 2017 28 Jun 22:56 -0500, mdblack98 wrote:
> I'd recommend getting rid of the tabs line in astyle.  That's what
> caused the problem with the indentation warnings I think plus tab
> spacings aren't portable.Just stick with 4 spaces per indent as the
> default or explicitly.

Done.  See my astyle-fixes branch:

https://github.com/N0NB/hamlib/commit/de2470d0b71245ea2a2f5df0fd610b628565fee5

I also changed it so it will bracket all one-line if, etc. statements.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Pull request merged**
