### PR TITLE
Enable Mic/Rear PTT when using rigctld.

### PR DESCRIPTION
**Pull request by dl1ycf**
When using rigctld for example with WSJT-X, it was not possible to choose whether PTT should enable the AF coming from the Microphone or Data Jacket of the TRX. So  changed RIG_PTT_RIG into RIG_PTT_RIG_MICDATA in netrigctl.c.

This should be harmless if at the very end there is a rig without this capability, since by default the PTT commands RIG_PTT_ON_MIC and RIG_PTT_ON_DATA should fall back to RIG_PTT_ON.

### CODE REVIEW

**Comment by N0NB** [comment]
To be honest, I don't know if this is as harmless as it might appear.

Would you consider posting this fix to the mailing list and solicit some other comments on this?

BTW, this PR is exactly correct.  Thanks.

**Comment by mdblack98** [comment]
I propose we add a new call get_vfo_targetable.
The problem is that init fills in the caps and WSJT-X only sees the netrigctl caps.
So...adding a new call that allows WSJT-X to retrieve the "real" value with a new function call should be completely harmless.
I also wonder if a get_caps is appropriate to copy the whole thing over.

**Comment by dl1ycf** [comment]
> Am 24.06.2017 um 14:08 schrieb Nate Bargmann <notifications@github.com>:
> 
> To be honest, I don't know if this is as harmless as it might appear.
> 
> Would you consider posting this fix to the mailing list and solicit some other comments on this?
> 

AFAIK, I have done so but I just did it once more, and explicitly
asked for comments on „harmless ?“.

I am fully aware that in some sense I rely on the code in src/rig.c:

int HAMLIB_API rig_set_ptt(RIG *rig, vfo_t vfo, ptt_t ptt)
{
<some lines omitted>
        case RIG_PTT_RIG:
                if (ptt == RIG_PTT_ON_MIC || ptt == RIG_PTT_ON_DATA)
                        ptt = RIG_PTT_ON;
                /* fall through */
        case RIG_PTT_RIG_MICDATA:


This means, if the „real rig“ downstream only has RIG_PTT_RIG
and not RIG_PTT_RIG_MICDATA, then if this function is called
with ptt== RIG_PTT_ON_MIC or ptt==RIG_PPT_ON_DATA this is
automatically mapped on RIG_PTT_ON.

Note that the symptom is severe: you cannot use WSJTX with
netrigctld for most rigs.

Yours,

Dl1YCF.

**Comment by N0NB** [comment]
Christoph, what do you think of Mike's suggested fix?

**Comment by dl1ycf** [comment]
> Am 28.06.2017 um 01:15 schrieb Nate Bargmann <notifications@github.com>:
> 
> Christoph, what do you think of Mike's suggested fix?
> 

This is now off-line so I must do this from memory:

short answer
============

I do not think it solves the problem I have found.

The reason is, that wsjt-x (and possibly other programs)
look at the Rig capabilites directly after registering
(that is, in the callback function of rig_list_foreach),
but as far as I can tell Mike is trying to update
the rig->caps data structure much later, upon
rig_open. This is why I updated the „read-only“
netrigcl_caps data structure, not taking care about
the „real“ rig.


long comment
============

The situation is indeed very complicated,
insofar as there is a 
problem with the netrigctl model (this has also
been brought up by Bill Sommerfeld). But here we
should step back and look at it:

I you wish that the virtual netrigctl „transceiver“ offers
the full functionality of the physical transceiver downstream,
which is controlled by a rigctld somewhere else, then this can
hardly be done within the current API, because you have to
ask the daemon about details of the physical rig very early
(upon registering) while you get the machine/port info much
later, upon rig_open. That means: when you would like to get
information about the physical rig, you not yet known where
it is.

So personally, I opt for a different viewpoint: netrigctl
is a transceiver with very limited capabilites that are
eventually mapped on the physical transceiver in the
rigctld daemon possibly at another corner of the world.
We can only make safe or reasonable ASSUMPTIONS about
the capabilites of the physical transceiver. „Safe“ means:
it does not harm if the assumption is not met. „Reasonable“
means: if we have to decide, we do such that it works for
the majority of rigs.

Coming back to the example at hand:

If it turns out that it is very difficult to teach netrigctl
how to handle two VFOs, because very different ways of
handling this are required for some rigs, then netrigctl
should be a trx model with a single VFO. Period. Keep
things simple.

One can certainly try to have a new rig model, say,
fancynetrigtl, which always connects to a fixed port on the
local machine. Then upon registering, we can look for such
a server with a small time-out value, ask for the
characteristics of the physical rig, fill in the data etc.
But this cannot be done within the current netrigctl
protocol.

Yours,
DL1YCF.

**Comment by mdblack98** [comment]
Thinking about this some more there are several possible solutions to this which won't break backwards compatibility.  I've ordered these in my preference from best to worst.
#1 Apps should not rely on rig->caps until AFTER init.  This is just a simple rule (this is my favorite though I have to prove it works).  In rig_open() we set the netrigctl caps to the underlying rig caps.  Then it will look just like the rig it's connected to.  WSJT-X and others just  have to move their caps logic after rig_init().
#2 set_caps() -- calling app forces caps update for netrigctl....it would basically be a no-op for any other rig.  Would only be valid after rig_open and could return the real caps too.
#3 get_caps() -- would return underlying rig caps....this would assume the setting of the rig caps is done under rig_open()
#4 get_ptt_type() -- this would fix this specific problem...not a very generic solution as other potential problems exist with other caps entries being wrong too.

None of these should break any software.  I have to test the idea of just doing a wholesale update of rig->caps from the underlying rig.  Only potential problem I see is incompatibilities between netrigctld caps and rig caps....so this is riskiest solution but I think the best.

netrigctld has worked on every rig I've ever tested until the FT-891/991 came out.  And the fix for those two rigs also needs a fix for WSJT-X too which I've submitted.

Two goals here:
#1 Maintain backwards compatibility
#2 Maintain future compatibility (by making the most generic solution)

**Comment by mdblack98** [comment]
Just looked through the code and there may be another simpler solution.
netrigctl rig_open copies info from dump_state that helps reflect the underlying rig.
So it would appear would could just add targetable_vfo to the dump_sate and have rig_init call rig_open.  It can even be called twice since it's really just copying dump_state.  No harm doing it twice.

**Comment by dl1ycf** [comment]
I shall present a cleaner solution in 1 min.

**Pull request closed without merging**
