### PR TITLE
Microham support. Use "uh-rig" for rig_pathname to talk to the

### PR DESCRIPTION
**Pull request by dl1ycf**
microHam device for CAT. If you want hardware PTT via the microham
device, use DTR method and ptt_pathname "uh-ptt".

Tested under MacOS and LINUX. Should compile under Win32,but I do not know how to "find" the
microham device there, so under Win32, it does not work (and does not harm). If you system does not have pthreads, it also does not work and does not harm.
I could only test it with Kenwood rigs (point-to-point protocol). For ICOM, there is a bus protocol that relies on SIGIO. This PR is implemented with this case in mind, but I could not verify that it works.

### CODE REVIEW

**Comment by N0NB** [comment]
I added mention of the 'uh-rig' keyword to the various document files.  The patchset is otherwise unchanged.

Thanks for your contribution, Christoph.

73, Nate

**Comment by N0NB** [comment]
I have to report that this is breaking my MinGW daily builds:

microham.c:16:18: fatal error: glob.h: No such file or directory
 #include <glob.h>
                  ^
compilation terminated.

When I ifndef it out then another header file and another fail with the same error.  I tried making the whole file conditional and then had a linker error.

My apologies for not vetting this more closely.

**Comment by dl1ycf** [comment]
> Am 12.09.2017 um 04:08 schrieb Nate Bargmann <notifications@github.com>:
> 
> I have to report that this is breaking my MinGW daily builds:
> 
> microham.c:16:18: fatal error: glob.h: No such file or directory
> #include <glob.h>
> ^
> compilation terminated.
> 
> When I ifndef it out then another header file and another fail with the same error. I tried making the whole file conditional and then had a linker error.
> 
> My apologies for not vetting this more closely.
> 

No no, this is entirely my duty. I only need the bug reports. It it easy *not* to include glob.h in MinGW, since
it is currently not used there. It is used in Linux and MacOS to define everything for the function glob that passes
through the file system (in our case, /dev) to look for files with specific names (in our case, device special files
that belong to microHam devices). I simply did not know that the glob() function does not exist in MinGW.

For the other issue, the global variabales, I change that into a function.
The issue here is that MinGW uses the read() system call for files, sockets, etc. but read_serial for serial devices.
Therefore, I ask in the WIN32 version of port_read() & friends whether the file descriptor possibly belongs to a
socket used by the microHam stuff. I will change this into a function call

if (is_uh_radio_fd(p->fd) {
    return read(p->fd, buf, count);
}

and declare the function is_uh_radio_fd locally. This is also the better solution for an „information hiding“
programming policy.

This results in updated files in hamlib/src, namely 
iofunc.c serial.c microham.c microham.h.

I include them in this mail. Does is compile now on MinGW?
Sorry to bother you, but I do not have access to such a system.




Yours,


+---------------------------------+----------------------------------+
| Prof. Christoph van Wüllen      | Tele-Phone (+49) (0)631 205 2749 |
| TU Kaiserslautern, FB Chemie    | Tele-Fax   (+49) (0)631 205 2750 |
| Erwin-Schrödinger-Str.          |                                  |
| D-67663 Kaiserslautern, Germany | vanWullen@Chemie.Uni-KL.De       |
|                                                                    |
| HomePage:  http://www.chemie.uni-kl.de/vanwullen                   |
+---------------------------------+----------------------------------+

**Comment by N0NB** [comment]
* On 2017 18 Sep 05:50 -0500, dl1ycf wrote:
> This results in updated files in hamlib/src, namely 
> iofunc.c serial.c microham.c microham.h.
> 
> I include them in this mail. Does is compile now on MinGW?
> Sorry to bother you, but I do not have access to such a system.

I did not receive the file attachments.

If you can run VirtualBox, you can run a Debian Jessie virtual machine
in it and could install the needed packages to test locally.  Is that
feasible for you?

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by dl1ycf** [comment]
> Am 21.09.2017 um 03:50 schrieb Nate Bargmann <notifications@github.com>:
> 
> * On 2017 18 Sep 05:50 -0500, dl1ycf wrote:
> > This results in updated files in hamlib/src, namely 
> > iofunc.c serial.c microham.c microham.h.
> > 

I will take care of this. I have installed msys2 together with
mingw on a windows-10 laptop. There are further problems e.g.
mingw does not have socketpair().

Note however, since there is no socketpair()
on MinGW, the microham support will behave as
if there were no microham device connected to the
computer.

I made a fresh fork of your repository, applied the changes
and pushed them back to github.com/dl1ycf/hamlib. You should see
a pull request now.

For me, it now compiles on MacOS *and* MinGW. On the next occasion
I will verify that it still works for me on MacOS, but I do not
doubt this.

Yours, 

+---------------------------------+----------------------------------+
| Prof. Christoph van Wüllen      | Tele-Phone (+49) (0)631 205 2749 |
| TU Kaiserslautern, FB Chemie    | Tele-Fax   (+49) (0)631 205 2750 |
| Erwin-Schrödinger-Str.          |                                  |
| D-67663 Kaiserslautern, Germany | vanWullen@Chemie.Uni-KL.De       |
|                                                                    |
| HomePage:  http://www.chemie.uni-kl.de/vanwullen                   |
+---------------------------------+----------------------------------+

**Pull request closed without merging**
