### PR TITLE
Change ic785x CIV address to the default of 0x8e

### PR DESCRIPTION
**Pull request by mdblack98**
Change ic785x CIV address to the default of 0x8e

### CODE REVIEW

**Comment by N0NB** [comment]
Should all the Yaesu changes be added?

**Comment by mdblack98** [comment]
Yaesu changes?  I thought it was just the one-liner CIV address for the 785x

DId I mess up the merge and commit?
de Mike W9MDB

**Comment by mdblack98** [comment]
OK....finally found the added yaesu patch stuff....you can add the FT-891.  I meant to submit that earlier but apparently forgot to do the pull request.Too many projects going on here :-) de Mike W9MDB

**Comment by N0NB** [comment]
I'm a bit nervous about applying this directly to my master branch.  I wonder if we've gotten out of sync since I did a rebase on your patches for the ft891 by compressing them into one patch?

May be you need to clone a new working repository from mine and then resubmit the pull request.

One thing Bill does is to always create a new branch in his repository that he sends his  pull requests  from.  That way his master always follows mine after I commit and push out his changes to the main Source Forge one.

**Comment by mdblack98** [comment]
OK...just do the CIV addr on the 785x for now.
I'll rebase and see why I'm offbase :-)
de Mike W9MDB

**Comment by N0NB** [comment]
Okay, I can cherrypick that one over.

**Comment by N0NB** [comment]
Cherry-picked, applied and pushed.  Thanks, Mike.

**Pull request closed without merging**
