### PR TITLE
Swig modifications

### PR DESCRIPTION
**Pull request by airween**
- added Lua binding and demo script
- added new example to pytest.py, to demonstrate set/get the float type level (eg. AF)

### CODE REVIEW

**Comment by N0NB** [comment]
Looks good.  I will pull and test it later this evening.  Thanks!

**Comment by N0NB** [comment]
Hi Ervin.

I'm getting the following build error:

make[1]: Entering directory '/home/nate/git/hlb/bindings'
/usr/bin/swig2.0 -lua  -DIN_HAMLIB -I../../hamlib/include -I../../hamlib/src -I../../hamlib/lib -I../../hamlib/bindings -o hamliblua_wrap.c \
    `test -f hamlib.swg || echo '../../hamlib/bindings/'`hamlib.swg
cstring.i not implemented for this target
make  all-am
make[2]: Entering directory '/home/nate/git/hlb/bindings'
  CC       Hamliblua_la-hamliblua_wrap.lo
hamliblua_wrap.c:2029:18: fatal error: misc.h: No such file or directory
 #include "misc.h"
                  ^
compilation terminated.
Makefile:695: recipe for target 'Hamliblua_la-hamliblua_wrap.lo' failed
make[2]: *** [Hamliblua_la-hamliblua_wrap.lo] Error 1
make[2]: Leaving directory '/home/nate/git/hlb/bindings'
Makefile:509: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/nate/git/hlb/bindings'
Makefile:567: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1


73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by airween** [comment]
Hi Nate,

it's interesting... I've grabbed the zip from my Github repo, and made a new checkout through Git, and both source compiled as well.

I don't know, why gives the GCC the number 2029 - in my case that exists in 2028:
```shell
$ pwd
/home/airween/src/github/hamlib/bindings
$ nl -ba hamliblua_wrap.c | less
  2026  #include <hamlib/rig.h>
  2027  #include <hamlib/rotator.h>
  2028  #include "misc.h"
  2029  
  2030  #include <limits.h>
```
Anyway, misc.h is exists, and it placed in $HAMLIBTREE/src/misc.h. It's interesting, why does the autotool generated the header paths as "-I../../hamlib/src", instead of "-I../src".

To see the differences, here are your and mine command line output (first is your, then mine, aligned the spaces to yours):
```shell
/usr/bin/swig2.0 -lua  -DIN_HAMLIB -I../../hamlib/include -I../../hamlib/src -I../../hamlib/lib -I../../hamlib/bindings -o hamliblua_wrap.c \
    `test -f hamlib.swg || echo '../../hamlib/bindings/'`hamlib.swg
/usr/bin/swig2.0 -lua  -DIN_HAMLIB -I../include           -I../src           -I../lib           -I../bindings           -o hamliblua_wrap.c \
	`test -f hamlib.swg || echo './'`hamlib.swg
```

I do not have any good idea - may be you're in wrong directory, when you type `autoreconf --install`, or `configure...`?
Does the Python binding (or another one) compiled successfully?


73, Ervin

**Comment by airween** [comment]
Hi Nate, you were able to try it again?

**Comment by N0NB** [comment]
I always build in a separate directory from the source tree to ensure VPATH builds work correctly.

Also, it is best to clean the source tree directory using Git with 'git clean -dxf'

and I clean the build directory with 'rm -rf *' (dangerous command in the wrong directory!).

Then I always use the 'autogen.sh' script in the main Hamlib directory to bootstrap the build system.  I usually call it from the build directory as '../hamlib/autogen.sh' and since it runs the configure script, configure options can be passed to it like '../hamlib/autogen.sh --with-lua-binding'.

All of that done I still get the same error regarding misc.h.  I wonder if the if else block you added at the top of the file is to blame.  None of the other bindings require that, and I don't know what it is doing, exactly.  It seems as though the LUA binding should follow the patterns of the others.

**Comment by airween** [comment]
Hi Nate,

I'm really sorry, but I still can't reproduce your issue. I've grabbed the ZIP from my repo (instead of git branch), to a brand new directory. Then I unpack the source, enter to it, and typed the command as you described. I've ran all commands through the `script` command:
`script -f compile.log`
which you can see here: http://pastebin.com/wXAhEZMm. (This paste lives for 1 month.) If you can share with me your output, please do it.
The if-else block at top of hamlib.swg doesn't affects the C compiler (nor preprocessor). The hamlib.swg doesn't participate the compile flow directly. Swig is just generates a C source file, which contains the "misc.h" header. The problem is in your case, that the preprocessor doesn't find the misc.h...

Note, that the if-else block just reliable to name of the Hamlib bindings. This avoids the name collosions, eg. if all bindings use same name (hamlib), then libtool will compile the "hamlib.so" shared object, and if all bindings uses same name, then they will encounters. This didn't came at this moment, becasue all existing bindings uses different names - but in case of Lua, libtool follows the standard way, and the shared object will called "hamlib.so". To avoid this, in this case, the name will be "hamliblua.so", and doesn't conflict with anything.

Note, that with these commands, you can try to compile the lua binding by hand:
```bash
/usr/bin/swig2.0 -lua  -DIN_HAMLIB -I../include -I../src -I../lib -I../bindings  -o hamliblua_wrap.c `test -f hamlib.swg || echo './'`hamlib.swg
/usr/bin/gcc -Wall -fPIC -shared -o Hamliblua.so hamliblua_wrap.c -I/usr/include/lua5.2 -L/usr/include -I../include/ -I../src/ -llua5.2 -lm -ldl
```

Hope we can clean this issue :)

73, Ervin

**Comment by N0NB** [comment]
If you try a Vpath build you can reproduce the problem.  This is important as the downstream packagers use Vpath build to create their packages.  Your patches build cleanly when build in the source tree directory but not when the build tree is in its own directory, as I've detailed above.

Notice that the include paths are incorrect in the Vpath build versus the in-tree builds:

`Making all in bindings
make[1]: Entering directory '/home/nate/test/hlb/bindings'
/usr/bin/swig2.0 -lua  -DIN_HAMLIB -I../../hamlib/include -I../../hamlib/src -I../../hamlib/lib -I../../hamlib/bindings -o hamliblua_wrap.c \
    `test -f hamlib.swg || echo '../../hamlib/bindings/'`hamlib.swg
cstring.i not implemented for this target
make  all-am
make[2]: Entering directory '/home/nate/test/hlb/bindings'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../hamlib/bindings -I../include  -I/usr/include/lua5.2 -I../include/hamlib -I../src  -fno-strict-aliasing -g -O2  -MT Hamliblua_la-hamliblua_wrap.lo -MD -MP -MF .deps/Hamliblua_la-hamliblua_wrap.Tpo -c -o Hamliblua_la-hamliblua_wrap.lo `test -f 'hamliblua_wrap.c' || echo '../../hamlib/bindings/'`hamliblua_wrap.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../hamlib/bindings -I../include -I/usr/include/lua5.2 -I../include/hamlib -I../src -fno-strict-aliasing -g -O2 -MT Hamliblua_la-hamliblua_wrap.lo -MD -MP -MF .deps/Hamliblua_la-hamliblua_wrap.Tpo -c hamliblua_wrap.c  -fPIC -DPIC -o .libs/Hamliblua_la-hamliblua_wrap.o
hamliblua_wrap.c:2029:18: fatal error: misc.h: No such file or directory
 #include "misc.h"
                  ^
compilation terminated.
Makefile:695: recipe for target 'Hamliblua_la-hamliblua_wrap.lo' failed
make[2]: *** [Hamliblua_la-hamliblua_wrap.lo] Error 1
make[2]: Leaving directory '/home/nate/test/hlb/bindings'
`

Now the in-tree build:

`Making all in bindings
make[1]: Entering directory '/home/nate/test/hamlib/bindings'
/usr/bin/swig2.0 -lua  -DIN_HAMLIB -I../include -I../src -I../lib -I../bindings -o hamliblua_wrap.c \
    `test -f hamlib.swg || echo './'`hamlib.swg
cstring.i not implemented for this target
make  all-am
make[2]: Entering directory '/home/nate/test/hamlib/bindings'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../include  -I/usr/include/lua5.2 -I../include/hamlib -I../src  -fno-strict-aliasing -g -O2  -MT Hamliblua_la-hamliblua_wrap.lo -MD -MP -MF .deps/Hamliblua_la-hamliblua_wrap.Tpo -c -o Hamliblua_la-hamliblua_wrap.lo `test -f 'hamliblua_wrap.c' || echo './'`hamliblua_wrap.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -I/usr/include/lua5.2 -I../include/hamlib -I../src -fno-strict-aliasing -g -O2 -MT Hamliblua_la-hamliblua_wrap.lo -MD -MP -MF .deps/Hamliblua_la-hamliblua_wrap.Tpo -c hamliblua_wrap.c  -fPIC -DPIC -o .libs/Hamliblua_la-hamliblua_wrap.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -I/usr/include/lua5.2 -I../include/hamlib -I../src -fno-strict-aliasing -g -O2 -MT Hamliblua_la-hamliblua_wrap.lo -MD -MP -MF .deps/Hamliblua_la-hamliblua_wrap.Tpo -c hamliblua_wrap.c -o Hamliblua_la-hamliblua_wrap.o >/dev/null 2>&1
mv -f .deps/Hamliblua_la-hamliblua_wrap.Tpo .deps/Hamliblua_la-hamliblua_wrap.Plo
/bin/bash ../libtool  --tag=CC   --mode=link gcc -fno-strict-aliasing -g -O2  -no-undefined -module -avoid-version  -o Hamliblua.la -rpath /home/nate/local/lib/lua/5.2 Hamliblua_la-hamliblua_wrap.lo ../src/libhamlib.la 
libtool: link: gcc -shared  -fPIC -DPIC  .libs/Hamliblua_la-hamliblua_wrap.o   -Wl,-rpath -Wl,/home/nate/test/hamlib/src/.libs -Wl,-rpath -Wl,/home/nate/local/lib ../src/.libs/libhamlib.so  -O2   -pthread -Wl,-soname -Wl,Hamliblua.so -o .libs/Hamliblua.so
libtool: link: ar cru .libs/Hamliblua.a  Hamliblua_la-hamliblua_wrap.o
libtool: link: ranlib .libs/Hamliblua.a
libtool: link: ( cd ".libs" && rm -f "Hamliblua.la" && ln -s "../Hamliblua.la" "Hamliblua.la" )
make[2]: Leaving directory '/home/nate/test/hamlib/bindings'
make[1]: Leaving directory '/home/nate/test/hamlib/bindings'
`

As I see it, the include path is incomplete for Vpath builds so this needs to be fixed before I can apply the pull request.

73, Nate

**Comment by N0NB** [comment]
Previous comments updated.

**Comment by airween** [comment]
Hi Nate,
thanks for clarification - now I think I've found the error: I wrote the CPPFLAGS for Lua binding as relative paths (eg. -I../src), but it needs to write as absolute. I've changed it to -I$(top_builddir) in all cases. See the commit: https://github.com/N0NB/hamlib/pull/32/commits/c1266ef44acb7c64587791f0e417a0254de61bfc
Hope now it will be good. Please check it again.

73, Ervin

**Comment by N0NB** [comment]
You got close, but it should be $top_srcdir instead of $top_builddir.

I'm not sure, but if you can, please rebase all of that together and issue a new pull request.

**Comment by airween** [comment]
Right, 've changed the macros. Now I'll close this pull request, and open a new one.

**Pull request closed without merging**
