### PR TITLE
Get rid of compiler warnings, adjust kenwood set_rf_level value.

### PR DESCRIPTION
**Pull request by dl1ycf**
This is the second round of changes to get rid of compiler warnings (some of my changes flipped through because of other updates).

Second: Now the correct RF power level is obtained for Kenwoods (corresponding change for an earlier fix to kenwood_set_rf_level.

Have a look at the change in kenwood/thd72.c. This is my best guess of what the original coder had in mind. The "if" as it stood was *never* executed, because a signed char cannot have the value 0xff.

### CODE REVIEW

**Comment by N0NB** [comment]
Do you want me to only apply 2b16912127 and then let you submit a new request for the microham code?

**Comment by dl1ycf** [comment]
> Am 15.07.2017 um 04:08 schrieb Nate Bargmann <notifications@github.com>:
> 
> Do you want me to only apply 2b16912 and then let you submit a new request for the microham code?
> 

Exactly. I did the pull request, and committed the microham stuff AFTER that. However,
this then goes into the pull request on github.com (i did not know that).
To make your life easier, I reverted the microham commit and will re-enter this
as soon as the small fixes are merged.

Sorry for this, I did not foresee the side effect. When pushing the microham code,
I will also announce this on the list, inviting comments.

Yours,

**Comment by N0NB** [comment]
* On 2017 17 Jul 04:59 -0500, dl1ycf wrote:
> 
> > Am 15.07.2017 um 04:08 schrieb Nate Bargmann <notifications@github.com>:
> > 
> > Do you want me to only apply 2b16912 and then let you submit a new request for the microham code?
> > 
> 
> Exactly. I did the pull request, and committed the microham stuff AFTER that. However,
> this then goes into the pull request on github.com (i did not know that).
> To make your life easier, I reverted the microham commit and will re-enter this
> as soon as the small fixes are merged.

I am going to guess that checking out master and creating a new branch
for microham and then issuing a new pull request will result in GitHub
creating a new request rather than appending to the prior one.

> Sorry for this, I did not foresee the side effect. When pushing the microham code,
> I will also announce this on the list, inviting comments.

I understand.  We're all learning.  :-)

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by dl1ycf** [comment]
I have now merged this with recent fixes to kenwood/kenwood.c (the sprintf ==> snprintf fix).

DL1YCF Chris.

**Comment by dl1ycf** [comment]
What a mess. I did not mean to close it, just wanted to leave the "merged it" note.

**Comment by dl1ycf** [comment]
> Am 15.07.2017 um 04:08 schrieb Nate Bargmann <notifications@github.com>:
> 
> Do you want me to only apply 2b16912 and then let you submit a new request for the microham code?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Since this obviously got stuck somehow (my fault), is it better to

a) delete my hamlib repo (this hopefully deletes the pending pull request)
b) make a fresh fork from your repository
c) apply change is small bits and start new pull requests?

This could re-sync the things.

Yours,

Christoph DL1YCF.

**Comment by N0NB** [comment]
* On 2017 07 Aug 03:53 -0500, dl1ycf wrote:
> 
> > Am 15.07.2017 um 04:08 schrieb Nate Bargmann <notifications@github.com>:
> > 
> > Do you want me to only apply 2b16912 and then let you submit a new request for the microham code?

> Since this obviously got stuck somehow (my fault), is it better to
> 
> a) delete my hamlib repo (this hopefully deletes the pending pull request)
> b) make a fresh fork from your repository
> c) apply change is small bits and start new pull requests?
> 
> This could re-sync the things.

I've done that in the past to recover from some glitch.  Just save your
diff in a safe place when you do so, create a new topic branch and go
again.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Pull request closed without merging**
