### PR TITLE
All licensing on the backends is now LGPL

### PR DESCRIPTION
**Pull request by mdblack98**
removed microtune
getopt.c removed
getopt.h replaced with LGPL version
getopt_long.c replaced with BSD version
Permissions from several authors to change to LGPL
Only GPL items are in tests now

### CODE REVIEW

**Comment by mdblack98** [comment]
Everything is LGPL now and compiles correctly

**Comment by N0NB** [comment]
If I recall, the inclusion of the 4 part BSD license in COPYING.BSD is problematic due to the advertising clause (Clause 3) which is considered incompatible with the GPL.  I'm not sure of its compatibility with the LGPL.  See:  https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_.28original_.22BSD_License.22.29

I'm not opposed to a BSD licensed alternative.  I think we should stay away from this version of the BSD license as it may well cause issues for various distributions.

**Comment by mdblack98** [comment]
Is there anything in there that is BSD?  Or is that just what you chose at the time?Can we just toss the BSD license?
de Mike W9MDB

**Comment by mdblack98** [comment]
Is there anything in there that's BSD licensed from somebody else?I see a lot of conditionals for compiling on BSD.  But my "find" command on windows is producing lots of garbage (a bug in mingw grep I think) so can't really look for BSD licensed components.
 de Mike W9MDB

**Comment by N0NB** [comment]
* On 2016 29 Oct 14:10 -0500, mdblack98 wrote:
> Is there anything in there that's BSD licensed from somebody else?I
> see a lot of conditionals for compiling on BSD.  But my "find" command
> on windows is producing lots of garbage (a bug in mingw grep I think)
> so can't really look for BSD licensed components.   de Mike W9MDB

Using "git grep BSD license" I get:

tuner/videodev2.h:17: *  BSD license as stated below:

Which is dual licensed.

I was remarking on your patch which is adding the COPYING.BSD file which
is the four clause BSD license that we want to stay away from if at all
possible.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by mdblack98** [comment]
I added that?  To be honest I have no idea why.Not even sure where I would've gotten it from.Please feel free to remove it.
de Mike W9MDB

**Comment by mdblack98** [comment]
I wasn't aware git had a grep....I was using the old "find . -type f -exec grep BSD {} \; -print" which has problems on windows.
I don't see where tuner2.h is included anywhere.Do we need it?  Or anything else in that directory?
de MIke W9MDB

**Comment by N0NB** [comment]
* On 2016 29 Oct 22:42 -0500, mdblack98 wrote:
> I added that?

I presume so as it is all green in the commit:

https://github.com/N0NB/hamlib/pull/26/commits/0714d172b7e9e7d61d82493a694788400a5da378

Also, the history shows it being added by you in this commit:

https://github.com/mdblack98/hamlib/commits/0714d172b7e9e7d61d82493a694788400a5da378/COPYING.BSD

> To be honest I have no idea why.  Not even sure where I would've gotten
> it from.  Please feel free to remove it.

It looks like you were trying to replace the presently GPL'ed
getopt_long.c with one from OpenBSD which appears to have come from
NetBSD per the versioning headers in the boilerplate area at the top of
the file.  If you can find one that is under a three clause BSD/X/MIT
licnese that does not have the onerous advertising clause, that would be
fine.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by N0NB** [comment]
* On 2016 29 Oct 22:53 -0500, mdblack98 wrote:
> I wasn't aware git had a grep....I was using the old "find . -type f
> -exec grep BSD {} \; -print" which has problems on windows.

It's rather handy as it only looks at files tracked by Git.  It also
ignores any files in the .gitignore file.  As Debian builds Git with
Perl Compatible Regular Expression (PCRE), I have my configuration set
to:

[grep]
        lineNumber = true
        patternType = perl

in $HOME/.gitconfig (on Windows it may be in quite a different location).

More documentation at:

https://www.kernel.org/pub/software/scm/git/docs/git-grep.html
                
> I don't see where tuner2.h is included anywhere.  Do we need it?  Or
> anything else in that directory?

I don't find a "tuner2.h".  The tuner directory contains "tuner.h",
however.

So far as I know, it's one of those specialized hardware backends.  No
harm in keeping it as someone, somewhere may be using it.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by mdblack98** [comment]
Ahh yes....memory is the 2nd thing to go....don't remember the first...
I found another replacement to try out.https://github.com/kubo/ya_getopt/



de Mike W9MDB

**Comment by N0NB** [comment]
* On 2016 30 Oct 08:04 -0500, mdblack98 wrote:
> Ahh yes....memory is the 2nd thing to go....don't remember the
> first...  I found another replacement to try out.
> https://github.com/kubo/ya_getopt/

It looks like a bit of work would be required to use it.  It's too late
to do this for a long overdue 3.1 release, so let's table this idea for
now.

Let's just do the textual changes that this patch set contains.  These
would be the files:

android/ltdl.c
android/ltdl.h
flexradio/dttsp.c
gnuradio/gr.c
gnuradio/graudio.c
gnuradio/mc4020.c
kit/elektor304.c
kit/funcube.c
kit/si570avrusb.c
src/rig.c

Also, let's not delete the microtune stuff yet.  It's not a part of the
default build and I think that removing something long-standing should
only be done as part of a major release, i.e. 4.0, 5.0, etc. where an
announcement is made well in advance that such a deletion will be taking
place.

If you can rebase with just the changes listed above and issue another
pull request, I would appreciate it.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by mdblack98** [comment]
OK...new pull request submitted.Looks like you can close the old pull request without merging.
de Mike W9MDB

**Comment by N0NB** [comment]
Closing at Mike's request.

**Pull request closed without merging**
