### PR TITLE
Added HPSDR backend

### PR DESCRIPTION
**Pull request by jaebird**
Added HPSDR backend which emulates TS-2000 over the network on TCP

### CODE REVIEW

**Comment by jaebird** [comment]
Updated backend per request. Should be ready to merge.

**Comment by N0NB** [comment]
* On 2017 21 Jan 15:41 -0600, jaebird wrote:
> Updated backend per request. Should be ready to merge.

Will do so this evening, Jae.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by N0NB** [comment]
Jae, I did a rebase which squashed both commits into one.  It has been pushed out to the repositories so it will be included in tomorrow's daily snapshot.

**Comment by jaebird** [comment]
Thanks Nate.

**Pull request closed without merging**
