### PR TITLE
Swig modifications

### PR DESCRIPTION
**Pull request by airween**
- added Lua binding and demo script
- added new example to pytest.py, to demonstrate set/get the float type level (eg. AF)

### CODE REVIEW

**Comment by N0NB** [comment]
Vpath build is working correctly.  Thanks.

On a build I see this warning:

`make[1]: Entering directory '/home/nate/test/hamlib/bindings'
/usr/bin/swig2.0 -lua  -DIN_HAMLIB -I../include -I../src -I../lib -I../bindings -o hamliblua_wrap.c \
    `test -f hamlib.swg || echo './'`hamlib.swg
**cstring.i not implemented for this target**
make  all-am
make[2]: Entering directory '/home/nate/test/hamlib/bindings'
  CC       Hamliblua_la-hamliblua_wrap.lo
  CCLD     Hamliblua.la
`

Is this important?

**Comment by N0NB** [comment]
I'm not seeing that warning with any of the other bindings.

**Comment by airween** [comment]
Hi Nate,

build result is good news.
The cstring.i error message isn't important - that's only a notice, that indicates that SWIG doesn't have string functions in C lang for Lua. It doesn't matter. We can ignore them like this:

old:
```c
    48	%include exception.i
    49	%include cstring.i
    50	#ifdef SWIGPYTHON
```
new form:
```c
    48	%include exception.i
    49	#ifndef SWIGLUA
    50	%include cstring.i
    51	#endif
    52	#ifdef SWIGPYTHON
```
but as I wrote, that doesn't matter.

Hope this helps.

**Comment by N0NB** [comment]
* On 2016 11 Dec 09:48 -0600, Ervin Hegedus wrote:
> Hi Nate,
> 
> build result is good news.  The cstring.i error message isn't
> important - that's only a notice, that indicates that SWIG doesn't
> have string functions in C lang for Lua. It doesn't matter. We can
> ignore them like this:
> 
> old:
> ```c
>     48	%include exception.i
>     49	%include cstring.i
>     50	#ifdef SWIGPYTHON
> ```
> new form:
> ```c
>     48	%include exception.i
>     49	#ifndef SWIGLUA
>     50	%include cstring.i
>     51	#endif
>     52	#ifdef SWIGPYTHON
> ```
> but as I wrote, that doesn't matter.
> 
> Hope this helps.

Yes, it does.  Thanks for the explanation, Ervin.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by N0NB** [comment]
I worked on this locally and rebased all of the patches and fixed a couple more bugs in the build system. The patch has been applied to the master branch and pushed to the repositories.

**Pull request closed without merging**
