### PR TITLE
[pihpsdr backend] Add support for AGC Levels

### PR DESCRIPTION
**Pull request by jaebird**
This PR adds AGC levels to the PiHPSDR backend.

### CODE REVIEW

**Comment by N0NB** [comment]
GCC is now throwing up a couple of warnings.  It seems that when declared variables are assigned and used in a switch statement that it gets all kinds of confused.  This doesn't affect the operation of the code, it just makes the compile process look ugly.  I like to quell such warnings so that problems become obvious.

Here are the messages:

```
  CC       pihpsdr.lo
../../hamlib/kenwood/pihpsdr.c: In function 'pihpsdr_get_level':
../../hamlib/kenwood/pihpsdr.c:760:25: warning: unused variable 'agclevel' [-Wunused-variable]
   int lvl, retval, ret, agclevel;
                         ^
../../hamlib/kenwood/pihpsdr.c:760:20: warning: unused variable 'ret' [-Wunused-variable]
   int lvl, retval, ret, agclevel;
                    ^

```

**Comment by jaebird** [comment]
I'll take care of it.

On Feb 9, 2017 6:46 PM, "Nate Bargmann" <notifications@github.com> wrote:

GCC is now throwing up a couple of warnings. It seems that when declared
variables are assigned and used in a switch statement that it gets all
kinds of confused. This doesn't affect the operation of the code, it just
makes the compile process look ugly. I like to quell such warnings so that
problems become obvious.

Here are the messages:

  CC       pihpsdr.lo
../../hamlib/kenwood/pihpsdr.c: In function 'pihpsdr_get_level':
../../hamlib/kenwood/pihpsdr.c:760:25: warning: unused variable
'agclevel' [-Wunused-variable]
   int lvl, retval, ret, agclevel;
                         ^
../../hamlib/kenwood/pihpsdr.c:760:20: warning: unused variable 'ret'
[-Wunused-variable]
   int lvl, retval, ret, agclevel;
                    ^


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/N0NB/hamlib/pull/52#issuecomment-278824196>, or mute
the thread

**Comment by N0NB** [comment]
* On 2017 09 Feb 19:16 -0600, jaebird wrote:
> I'll take care of it.

Thanks, Jae.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by jaebird** [comment]
It looks like they were unused variables after all! Should be clean now.

**Comment by N0NB** [comment]
Applied and pushed.  Thanks, Jae.

**Pull request closed without merging**
