### PR TITLE
Icr10 20

### PR DESCRIPTION
**Pull request by malcolmh**
Icom IC-R10 & 20 testing complete. Move to Beta

### CODE REVIEW

**Comment by malcolmh** [comment]
Nate, This is a cleaned-up version with the conflicts removed.

**Comment by N0NB** [comment]
* On 2017 12 Apr 02:55 -0500, Malcolm Herring wrote:
> Nate, This is a cleaned-up version with the conflicts removed.

I still have a group of commits in that branch that were already
committed in commit a8e89505e38a20c879b1d4afaa814a4338413ffa.

Please, just send me the modified file(s) for the new feature for now.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by malcolmh** [comment]
Nate, did you receive the files?

**Comment by N0NB** [comment]
* On 2017 01 May 00:35 -0500, Malcolm Herring wrote:
> Nate, did you receive the files?

Hi Malcolm.

No, I never did.  Please send them directly to n0nb@n0nb.us

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by N0NB** [comment]
Sorry for the delay, Malcolm, been quite busy as is usual in spring/summer for me.

I applied the two files (icom.c only had formatting changes so I didn't apply it) and have pushed them out.

You will want to set my GitHub repository as an upstream in your local Git repository so you can pull from it and bring your master up to date with mine (replay if you'd like further instructions).  After that you can then create new branch for another set of changes.

73, Nate

**Pull request closed without merging**
